name: Github Release create, update, and upload assets
description: Github Action to create, update, or add files to Github Releases

inputs:
  # Exposed Github API inputs (identical to ones consumed by Github API):
  #   https://developer.github.com/v3/repos/releases/#create-a-release
  # NOTE: No defaults set for these, to avoid override on update due to the impossibility
  #       of distinguishing between default, and user input.

  tag:
    description: A tag for the release
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  color: 'green'
  icon: 'anchor'
